force-app/main/default/objects/Partner_Performance_Review__c/Partner_Performance_Review__c.object-meta.xml
<CustomObject>
    <label>Partner Performance Review</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Partner Performance Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Performance Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Overall_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Overall_Feedback__c</fullName>
    <label>Overall Feedback</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Overall_rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_rating__c</fullName>
    <inlineHelpText>1 being low; 5 being high</inlineHelpText>
    <label>Overall rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Performance Reviews</relationshipLabel>
    <relationshipName>Partner_Performance_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Partner_Business_Planning__c.field-meta.xml
<CustomField>
    <fullName>Partner_Business_Planning__c</fullName>
    <label>Partner Business Planning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Needs Improvement</fullName>
            </value>
            <value>
                <fullName>Low Quality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Partner_Implementation_Description__c.field-meta.xml
<CustomField>
    <fullName>Partner_Implementation_Description__c</fullName>
    <label>Partner Implementation Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Performance_Review__c/fields/Partner_Quality__c.field-meta.xml
<CustomField>
    <fullName>Partner_Quality__c</fullName>
    <label>Partner Quality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerReviewController.cls
public with sharing class PartnerReviewController {
    public PartnerReviewController() {

    }

   
    @AuraEnabled(cacheable=true)
    public static List<Partner_Performance_Review__c> getPartnerReviews(string partnerAccountId){
    try {

        return [SELECT Id, Name, CreatedById, CreatedBy.Name,CreatedBy.email, Overall_Feedback__c, Overall_rating__c,
         Partner_Account__c,Partner_Account__r.Name, Partner_Business_Planning__c, Partner_Implementation_Description__c, 
         Partner_Quality__c FROM Partner_Performance_Review__c WHERE Partner_Account__c =: partnerAccountId];
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
}
}