force-app/main/default/objects/Account/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Type_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Type</label>
    <referenceTo>Partner_Type__c</referenceTo>
    <relationshipLabel>Partner Type</relationshipLabel>
    <relationshipName>PartnerTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Type__c/Partner_Type__c.object-meta.xml
<CustomObject>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataFix.cls
public with sharing class DataFix {
    public DataFix() {

    }
    

    public static void UpdatePartnerType() {

        try {
             
            Partner_Type__c techPartner = [SELECT ID FROM Partner_Type__c WHERE Name = 'Technology Partner'];
            Partner_Type__c marketingPartner = [SELECT ID FROM Partner_Type__c WHERE Name = 'Marketing Partner'];
            
            List<Account> partnerAccs = [SELECT Id, Partner_Type_Lookup__c, Name FROM Account
            WHERE Partner_Status__c IN ('Active','Inactive','Pending')];

            for (Account acc : partnerAccs) {

                
                acc.Partner_Geo_Location__Latitude__s = 51.505;
                acc.Partner_Geo_Location__Longitude__s = -0.09;
                if(acc.Name == '6sense' || acc.Name == 'MailChimp' || acc.Name == 'Demandbase')
                {
                    acc.Partner_Type_Lookup__c = marketingPartner.Id;
                }
                else
                {
                    acc.Partner_Type_Lookup__c = techPartner.Id;
                }
            }
            
            System.debug('acctoUpdate::' + partnerAccs);
            update partnerAccs;


        } catch (Exception ex) {
            
            System.debug('The following exception has occurred: ' + ex.getMessage());
        }
        
    }
}